### ISSUE TITLE
Allow roam_alias to be a YAML formatted array

### ISSUE THREAD

**Issue by dschapman** [nobiot/md-roam#19]
Currently this value accepts the same values as org-roam does -- a space delimited list. I'm curious whether it would be possible to format this as a regular array in the YAML frontmatter. 

For example:
`roam_alias: ['alias 1', 'alias 2', 'alias 3']`

I'm playing around with using md-roam in the notes folder on my gatsby website. And the markdown format of md-roam is _almost_ 100% compatible except for the roam_alias values which break when they're parsed by gatsby because they're not correctly formated YAML arrays.

**Comment by nobiot** [comment]
Oh, thanks for this. Parsing of the space delimited list is parsed in `org-roam`. I need to double check this, and play with its implementation to see if it can be easily adjusted for Md-roam.  It is being ["simplified"](https://github.com/org-roam/org-roam/pull/762); I will look at it more carefully, hopefully over the weekend.

**Comment by nobiot** [comment]
@dschapman, 
#21 will add the feature. Would you mind testing the branch?
My initial tests look OK.

**Comment by nobiot** [comment]
Thanks for pointing out to me about the YAML syntax. I was not fully aware of it. 
Now merged with the master, and updated README, etc. 
Closing this issue for now, but if you see some issues, let me know.

**Comment by dschapman** [comment]
Thanks for addressing this. Org-Roam worked when I used that format where it hadn’t before.

**Comment by nobiot** [comment]
@dschapman thanks for confirming that the new version works
