### ISSUE TITLE
(fix) `org-roam-switch-to-buffer` does not seem to list markdown files

### ISSUE THREAD

**Issue by nobiot** [nobiot/md-roam#23]
Test it and if issue, fix it.

**Comment by ehamberg** [comment]
I'm able to reproduce this issue here with some informal, manual testing.

**Comment by nobiot** [comment]
@ehamberg, thank you for confirming. In a very early version, I had fixed it but probably at one of the breaking changes, I dropped it accidentally. I'll come back to it and fix it -- should not be a big of an issue...

**Comment by nobiot** [comment]
@ehamberg, happy for you to tets, if you have a bit of spare time :)

**Comment by ehamberg** [comment]
@nobiot Seems to work now! Thank you so much for creating this, btw. I was really happy when I saw this project! 😄

**Comment by nobiot** [comment]
@ehamberg , thank you for your kind words. Happy that it can be useful for someone other than me :)
