### ISSUE TITLE
How to select what type should I insert note .org or .md

### ISSUE THREAD

**Issue by bimawa** [nobiot/md-roam#51]
After read issue #49 .  I found the next solution for force file, which I insert, create with .md format:
```
(setq org-roam-file-extensions '("md" "org"))
```

But md-roam is addon for org-roam. And I use it only for documentations, but notes I prefer hold in org files. How can I select the type of file for org-roam?

**Comment by nobiot** [comment]
I just create some notes as .org files; others, .md files. I don't use org-roam-capture or -file to create a new notes.

**Comment by bimawa** [comment]
Ohh ok.

**Comment by searene** [comment]
I found a solution to select a file type each time I insert a note using `org-roam-node-insert`. Just add the following code to your config file:

```lisp
(add-to-list 'org-roam-capture-templates
      '("m" "Markdown" plain "" :target
          (file+head "%<%Y-%m-%dT%H%M%S>.md"
  "---\ntitle: ${title}\nid: %<%Y-%m-%dT%H%M%S>\ncategory: \n---\n")
      :unnarrowed t))
```

Here is my complete configuration, I'd be happy if it's helpful to anyone.

```lisp
(use-package! md-roam
  :after (org-roam)
  :demand t
  :custom
  (org-roam-file-extensions '("md" "org"))
  :config
  ;; md-roam-mode must be active before org-roam-db-sync
  (md-roam-mode 1)
  ;; autosync-mode triggers db-sync. md-roam-mode must be already active
  (org-roam-db-autosync-mode 1)
  (add-to-list 'org-roam-capture-templates
      '("m" "Markdown" plain "" :target
          (file+head "%<%Y-%m-%dT%H%M%S>.md"
  "---\ntitle: ${title}\nid: %<%Y-%m-%dT%H%M%S>\ncategory: \n---\n")
      :unnarrowed t)))
```
