### ISSUE TITLE
markdown-mode typo causes error when building md-roam on doom

### ISSUE THREAD

**Issue by tokinifubara** [nobiot/md-roam#55]
https://github.com/nobiot/md-roam/blob/ae042451253c0cfa796ef8bacc198f503f58f9ac/md-roam.el#L9

Managed to fix it on my local file by fixing the typo.
```
-  ;; Package-Requires: ((emacs "27.1") (org-roam "2.1.0") (markdow-mode "2.5"))
+  ;; Package-Requires: ((emacs "27.1") (org-roam "2.1.0") (markdown-mode "2.5”))
```

**Comment by nobiot** [comment]
Thanks! Should be fixed now.

**Comment by tokinifubara** [comment]
Thanks for getting on it so quickly and all your work on the package!
