### ISSUE TITLE
Support for org-roam-db-version version 18

### ISSUE THREAD

**Issue by sync0** [nobiot/md-roam#56]
First, thank you so much for this package. As a user of Obsidian.md, I am really looking forward to integrating this package into my workflow. Without proper support for a database, Emacs' markdown-mode is just not usable as a Zettelkasten.

I was trying to get md-roam working today, but I noticed that it only supports up to org-roam-db-version 17. Org-roam's (v2.1) current version is 18, so I was wondering if you could add support for this version as well. 

Again, thank you so much for this package. The org format is much more powerful than markdown, but the lack of cross-platform support for org files (essentially, you are stuck with Emacs if you want to work properly with them) doesn't accommodate my current Zettelkasten workflow.

**Comment by nobiot** [comment]
Sure. Db version 18 was introduced only yesterday in my time zone https://github.com/org-roam/org-roam/pull/1963.

This sort of “warning” is exactly the reason for this check. 

I’ll review the change and try to support version 18 as soon as I can. Give me some time.

**Comment by nobiot** [comment]
@sync0 Thank you for the note. Should be fine with the latest commit. Let me know if you have issues.
