### ISSUE TITLE
Remove ID Properties on capture template

### ISSUE THREAD

**Issue by romariorobby** [nobiot/md-roam#61]
Is that possible to remove ID Properties on top of the md file in capture template? 
![image](https://user-images.githubusercontent.com/40323094/159118449-8e966f32-6011-4a51-aae4-f818902e81c0.png)
Heres my template
![image](https://user-images.githubusercontent.com/40323094/159118621-6d6f6c49-fa4f-4e4f-b265-8ce300369fa7.png)

**Comment by nobiot** [comment]
Good timing. Was just working on a new patch for this issue. Try the latest commit.
It's also the same issue as the last part of #60.
Let me know how you go. Thank you.

**Comment by romariorobby** [comment]
Great. It worked perfectly. Thank you so much!
