### ISSUE TITLE
[FR] Please get into Melpa

### ISSUE THREAD

**Issue by wakatara** [nobiot/md-roam#63]
It would be nice if this was already in melpa instead of a manual install so that it could be managed by straight/use-package etc.

thanks!

**Comment by nobiot** [comment]
Thank you for comment and encouragement. For this request, I’m not currently thinking of bringing md-roam to MELPA; it started as my personal hack to scratch my own back and would like to keep it that way for now.

**Comment by nobiot** [comment]
By the way, I thought Straight could manage packages on GitHub (?)

**Comment by wakatara** [comment]
OMG, you're so right. I'm embarrassed I did not think of this. Too use to using the `(use-package X :straight t )` with it from my previous config.
