### ISSUE TITLE
[FR] Changing default link style to markdown + :PROPERTIES: on new file generation

### ISSUE THREAD

**Issue by wakatara** [nobiot/md-roam#64]
So far, kinda loving what you're doing with md-roam here, but having a few issues setting this up to move completely off of org mode documents to markdown (thank you so much for writing this btw!).

I should be clear, my goal here is to completely convert everything over to markdown and use that as the default rather than org-mode.

1. When I use the default insert node command `C-c n i` the link that is inserted in my markdown document is (unfortunately) org-mode style. How does one override that?

2.  When I generate a new document with say `org-roam-dailies-find-today` the document inserts my markdown yaml well enough (yay!) but still inserts a `:PROPERTIES:` drawer with this ID at the top of the doc rather than in my yaml. How do I override that? 

Anyhow thanks for the time you've spent on this. I really want to have markdown (and perhaps taskpaper) as my standard rather than org-mode docs.

**Comment by nobiot** [comment]
Thank you for your encouraging comment. 

- For 1, could you make sure that you have `md-road-mode` on? It's a global  minor mode; it should turn on an advice for `org-roam-node-insert`, which should be effective when you are in `org-roam-directory`. If it is on, you might not be in `org-roam-directory` for the markdown file in which you call it. It should insert a link with the wikilink format ``[[title of the inserted node]]`` like the image below.

  ![Screenshot from 2022-04-17 19-04-43](https://user-images.githubusercontent.com/12507865/163720723-6dda3f56-862c-4835-bafa-f4ee70ae5e15.png)

- For  2, could you ensure to have the latest commit, please? I've fixed the same issue for `org-roam-node-find` and `-capture` in one of the most recent commit.  
  I don't use Dailies, so I don't test it and don't intend it to extend md-roam for it. This is a main reason why I don't share the package on MELPA -- I don't intend to and don't have capacity in supporting the features of Org-roam that I don't use -- dailies is one of them. I was hoping Org-roam is designed to reuse the same function as much as possible across different `insert-node` features -- if dailies do not go through the same method, I'd suggest you to log a feature request upstream.

For `md-roam`, if you turn on the minor-mode, `(add-hook 'org-roam-capture-preface-hook #'md-roam-capture-preface)` should do the trick. If you don't see it, then I suspect your version is not the current.

**Comment by wakatara** [comment]
Took in the latest commit and used the hook and things seem to be working fone now. 

thanks!

**Comment by nobiot** [comment]
@wakatara sorry if I was not clear about the hook but you shouldn’t have to do it yourself — it’s part of md-roam
