### ISSUE TITLE
Cursor placed at the start of the last header line prevents use of templates

### ISSUE THREAD

**Issue by iod-ine** [nobiot/md-roam#67]
When a new note is created, the cursor is placed at the beginning of the line with the last entry in the YAML header. With the default config for a template markdown note, which in my Doom setup looks like

```emacs-lisp
(setq org-roam-capture-templates
      '(("d" "default" plain
         ""
         :target (file+head "${slug}.md"
                            "---\ntitle: ${title}\nid: %<%Y-%m-%dT%H%M%S>\ncategory: #draft\n---\n")
         :immediate-finish t
         :unnarrowed t)))
```

the new note is opened like this:

<img width="387" alt="Screen Shot 2022-07-07 at 21 02 12" src="https://user-images.githubusercontent.com/62653164/177844234-001020ac-e5cb-49d6-9b6a-c48cd8b2d50e.png">

When I try to use a template instead of an empty string either using a single string

```emacs-lisp
(setq org-roam-capture-templates
      '(("d" "default" plain
         "- `Relevant notes`\n\n# ${title}\n\n%?\n\n*Reference (Author, Date)*"
         :target (file+head "${slug}.md"
                            "---\ntitle: ${title}\nid: %<%Y-%m-%dT%H%M%S>\ncategory: #draft\n---\n")
         :immediate-finish t
         :unnarrowed t)))
```
or a template file with the same content as that string

```emacs-lisp
(setq org-roam-capture-templates
      '(("d" "default" plain
         (file "~/Documents/Slip-box/Templates/Zettel.md") 
         :target (file+head "${slug}.md"
                            "---\ntitle: ${title}\nid: %<%Y-%m-%dT%H%M%S>\ncategory: #draft\n---\n")
         :immediate-finish t
         :unnarrowed t)))
```

the content is inserted at this cursor position like this:

<img width="404" alt="Screen Shot 2022-07-07 at 20 31 37" src="https://user-images.githubusercontent.com/62653164/177845263-ec243e4f-a2f1-4c38-8ce4-1d7903720535.png">

Note how within this incorrectly inserted template the cursor is positioned as expected at the `%?`.

With plain org-roam templates defined like this work fine. Sorry if this is a misconfiguration on my part, I am very new to Emacs.

**Comment by iod-ine** [comment]
I have just realized that the problem is in the `:immediate-finish t`.

**Comment by nobiot** [comment]
So problem solved for you? It’s not part of Md-roam and I don’t have a problem. Not sure what I can do to help you…

**Comment by iod-ine** [comment]
@nobiot It's not, but I've opted to change my workflow to exclude the situations where it can occur. And it's 100% not on the md-roam side, so I'll close this. Sorry and thank you!
