### ISSUE TITLE
md-roam-follow-wiki-link looks for node without stripping 'roam:' prefix

### ISSUE THREAD

**Issue by arnab-basu** [nobiot/md-roam#68]
Steps to reproduce:
1. After setting up md-roam, insert link to org-roam node (.org file) using completion
2. Link inserted looks like `[[roam:2022_06_10]]`
3. With cursor on link press enter
4. Capture process is activated. `*Messages*` shows `No org-roam node found for "roam:2022_06_10"`
5. Remove `roam:` from wikilink manually
6. With cursor on link press enter
7. Expected node is opened

Expected:
- should not need to strip `roam:` manually

**Comment by nobiot** [comment]
> should not need to strip roam: manually

You don’t need it: just normal Markdown-mode wiki.

**Comment by arnab-basu** [comment]
Right but it's being added by the link completion functionality, I'm guessing [this code](https://github.com/org-roam/org-roam/blob/main/org-roam-node.el#L785)? How do I disable the prefix addition in markdown files?

I'm using doom emacs and [this](https://github.com/nobiot/md-roam/issues/59#issuecomment-982770650) config.

**Comment by arnab-basu** [comment]
I recorded a gif to explain what is hapenning. Let me know if this helps

![OrgMdRoamLinking](https://user-images.githubusercontent.com/28657874/178105826-71a602cf-93cc-492e-8847-624f06718d29.gif)

**Comment by nobiot** [comment]
You'd need to turn off `org-roam-completion-everywhere`. I don't use it so I don't support it (Md-roam is just a personal package shared with others as is; hence, not on MELPA or others) -- I confirmed this is the case.

Having said this, I will have a look if this can be easily done.

**Comment by nobiot** [comment]
Done. You might need to relaunch Emacs after updating md-roam. It's lightly tested and don't have much capacity today to do more -- I might have broken something, especially if you use both Org and Markdown. Let me know if you notice something.

**Comment by arnab-basu** [comment]
Initial testing shows that this is working fine. Will comment here if I see anything that does not work.

Thanks a lot for your great work and responsiveness!!
