### ISSUE TITLE
Convert roam markdown files to org

### ISSUE THREAD

**Issue by morphykuffour** [nobiot/md-roam#69]
I have been using this package for a while but It has been prompting to allow readonly files for all my markdown files  every time I open emacs. Is there a way to convert md-roam markdown files to org mode and keep all the links intact.

**Comment by nobiot** [comment]
I’d suggest pandoc. You could also consider obsidian.el

**Comment by nobiot** [comment]
I don’t have the issue you mention, though…

**Comment by morphykuffour** [comment]
> I’d suggest pandoc. You could also consider obsidian.el

I found this [link](https://emacs.stackexchange.com/questions/5465/how-to-migrate-markdown-files-to-emacs-org-mode-format) useful in converting my documents but I will post a video to this thread showing the other issue I was describing.

**Comment by morphykuffour** [comment]
Let me know if you can view the video with this [link](https://www.dropbox.com/s/ivw1pucbjvuaju9/2022-07-28-14-34-18.mkv?dl=0)

**Comment by nobiot** [comment]
Thank you. I have seen the video. I think I know what is happening, though it's a bit difficult for me to reproduce consistently on my end. 

In any case, I think I have fixed the issue with the latest commit. Would you mind testing it on your end?

**Comment by morphykuffour** [comment]
Yes I tested and it works as expected, thank you the help.
