### ISSUE TITLE
[Bug] Agenda C-c C-t binding throwing error with md-roam

### ISSUE THREAD

**Issue by wakatara** [nobiot/md-roam#76]
I downgraded to 28.2 recently and reinstalled md-roam. It seems to be working fine, but whenever I try to use the `C-c C-t` binding in agenda to mark a task as changed, I am receiving the following error. It only happens if md-roam is loaded and active:

``` elisp
apply: Wrong number of arguments: ((t) nil "Used in `org-roam-node-open' to avoid error.
invalid-regexp \"Invalid regular expression\"." (if (md-roam--markdown-file-p (buffer-file-name (buffer-base-buffer))) (progn t))), 1
```

I am unsure if this has something to do with org-roam-node-open conflicting with the keybind for agenda but I do not think so, and as noted, it only happens if md-roam is installed and active. 

OS: OSX 13.2
Emacs: 28.2 Railwaycat homebrew
md-roam: installed via straight 

nb: I do have org-super-agenda loaded as well, but the above error occurs both when it is active and when it is not.

**Comment by wakatara** [comment]
Apologies, I typo-ed. That should have read `C-c C-t`. It is, as far as I know, the default binding to bring up task completion in org-agenda. on a todo item in the agenda (I just checked my keymaps and don't see anything that would change that... and really, org-agenda is the bomb. It runs my life... try it!... =] ).

So, for me, it normally pops up the following when I trigger it on a TODO item (see the bottom minibuffer in the screen):

<img width="1440" alt="Screenshot 2023-02-13 at 9 23 14 PM" src="https://user-images.githubusercontent.com/2866/218484064-38d860ce-dbbc-4f71-a3fa-6bb156824a4f.png">

**Comment by nobiot** [comment]
What command is bound to C-c C-t? On my end it’s org-agenda-todo and the same as “t”, and I don’t get the menu in minibuffer. I have no problem with this command.

**Comment by wakatara** [comment]
I think if you have fast-key access built for the TODOS you get the minibuffer, a la the org-agenda manual 

I am guessing adding this will reproduce the error on your side (from my config)

``` elisp
  (setq org-todo-keywords '((type "TODO(t@/!)" "WIP (w@/!)" "FUP (@/!)" "GAVE(g@/!)" "|" "DONE(d@/!)" "KILL(k@/!)")))
```

> C-c C-t (org-todo)
>
>    Rotate the TODO state of the current item among
>
>    ,-> (unmarked) -> TODO -> DONE --.
>    '--------------------------------'
>    If TODO keywords have fast access keys (see [Fast access to TODO states](https://orgmode.org/manual/Fast-access-
>    to-TODO-states.html)), prompt for a TODO keyword through the fast selection interface; this is the default behavior 
>    when org-use-fast-todo-selection is non-nil.
> The same state changing can also be done “remotely” from the agenda buffer with the t command key (see [Commands > in the Agenda Buffer](https://orgmode.org/manual/Agenda-Commands.html)).

**Comment by nobiot** [comment]
I tried your `org-todo-keywords`. No error in the agenda when changing the state...

**Comment by wakatara** [comment]
I am going to be really happy when I figure out which package I am using is interfering with the mojo on md-roam.  8-/   (I'm assuming it's not some sort of weird mac thing... ).

**Comment by KengChiChang** [comment]
I'm having the exact same problem. The problem will go a way if I disable md-roam-mode in Org agenda mode. How can I do that in config.el?

**Comment by wakatara** [comment]
@KengChiChang Phew... ok, so I'm not insane... that is some comfort.

Can you list your OS and emacs and org-mode version and such. 

As well, since @nobiot  is not able to reproduce it, we probably need to puzzle out what packages we may have in common that may be causing the conflict (I doubt it's an org-mode configuration variable but curious as to what you may think.).

**Comment by nobiot** [comment]
Can you paste the whole backtrace, please? Turn on toggle-debug-on-error and hit the error; you should get a more detailed error message and “call stack”

**Comment by wakatara** [comment]
Of course! (I have to admit I am still figuring out how to get emacs to do things like debugs to run errors down to ground.). 

This is what I get when I have that on and what shows up in the *Backtrace* minibuffer:

``` elisp
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) nil "Used in `org-roam-node-open' to avoid error.\ninval..." (if (md-roam--markdown-file-p (buffer-file-name (buffer-base-buffer))) (progn t))) 1)
  md-roam-do-not-show-context(agenda)
  apply(md-roam-do-not-show-context agenda)
  org-show-context(agenda)
  org-agenda-todo(nil)
  funcall-interactively(org-agenda-todo nil)
  call-interactively(org-agenda-todo nil nil)
  command-execute(org-agenda-todo)
```

I should point out that I am only altering tasks that are org-mode TODOs of various state. 

lemme know if you need me to do anything more on this front!

**Comment by KengChiChang** [comment]
I'm on M1 Mac 12.6 (Monterey), Emacs 28.2 [jimeh/emacs-builds](https://github.com/jimeh/emacs-builds), Org 9.6, Org-Roam 74422df, md-roam from straight.

Here's my backtrace

```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  md-roam-do-not-show-context(agenda)
  apply(md-roam-do-not-show-context agenda)
  org-show-context(agenda)
  org-agenda-todo(nil)
  funcall-interactively(org-agenda-todo nil)
  command-execute(org-agenda-todo)
```

**Comment by nobiot** [comment]
`md-roam-do-not-show-context` is not part of `md-roam` that I share in this repo. Where does it come from?

**Comment by nobiot** [comment]
Oh wait. I retract what I said. Let me have a look...

**Comment by nobiot** [comment]
I still can't reproduce the issue, but by the look  of the backtrace, https://github.com/nobiot/md-roam/commit/9ccd8fee00ebea28dfdc1f6d6ffe3d312973ceb7 should fix the issue.

**Comment by wakatara** [comment]
Woo! Just did a `straight-pull packcage` on it and it definitely fixed my issue. Yeyyyy! Thank you so much!!!

**Comment by KengChiChang** [comment]
Works like a charm. Thanks so much!

**Comment by nobiot** [comment]
Thank you both for confirming.
