### ISSUE TITLE
Run into "range error" while opening a .md file

### ISSUE THREAD

**Issue by hy-zhao23** [nobiot/md-roam#80]
Hi, Here is what I get in my emacs when I open and click a .md file in a md roam project.
```
 The error was: (error "rx ‘**’ range error")
 Backtrace:
"  backtrace-to-string(nil)
  org-element-at-point()
  org-back-to-heading(t)
  org-back-to-heading-or-point-min(t)
  org-roam-id-at-point()
  org-roam-ui--update-current-node()
"
 Please report this to Org mode mailing list (M-x org-submit-bug-report). 
```

I have reported this to org-mode contributors. And they think it might because md-roam package modified `org-roam-buffer-p' and caused the breakage.

Hope this could help you to fix the issue.

**Comment by nobiot** [comment]
Does this happen any md file?

**Comment by nobiot** [comment]
Does it happen when you open a md file in a directory without .dir-local.el?

Does it happen when you open every md file? (I am suspecting that the content of the file may influence the behavior).

**Comment by nobiot** [comment]
Also, whats your org version ans Emacs version?

**Comment by nobiot** [comment]
Additionally, you seem to be opening a md file from org-roam-ui. Does the problem happen if you open the same file from within Emacs via find-file?

**Comment by melody-yu23** [comment]
Org: 9.7
Emacs: 28.2

It only happens for the first file visiting with `SPC-p-p`. And I can't trigger it now after I defined `org-roam-directory`, which is useless for my workflow. I will follow up once I can reproduce it again. Thank you!

**Comment by melody-yu23** [comment]
It is resolved after I disable `org-roam-db-autosync-mode`, which caused the conflicts I guess. Thanks for your help!

**Comment by melody-yu23** [comment]
After I disabled definition of directory, turn off `org-roam-db-autosync-mode` and tried to use `dir-locals.el` to enable multiple projects. The problem appears again when I tried to open another file with `SPC-n-r-f`. 
Please check the error message below:
```
Warning (org-element-cache): org-element--cache: Org parser error in 23-08-10-explanation.md::215. Resetting.
 The error was: (error "rx ‘**’ range error")
 Backtrace:
nil
```

**Comment by dltacube** [comment]
This might be unrelated but I ran into the same error when adding a markdown file containing a `#+title: 1` inside of a codeblock. Removing the line or even adding `;;` for comments resolved the issue.

**Comment by nobiot** [comment]
Hopefully [d05d867](https://github.com/nobiot/md-roam/commit/d05d86756935ef706de531bbf140d519b1805070) fixes the issue. Let me know how you go. Closing for now.
