### ISSUE TITLE
wikilinks dont work

### ISSUE THREAD

**Issue by Ravenightwing** [nobiot/md-roam#84]
It is fine with \[title](path.md), but would not work as [[wikilinks]]. I can find the nodes with `org-roam-node-find` and other functions, but nodes referred by wiki links simply do not work (you cannot open the links, and they won't appear as backlinks).
Here is my configuration.
```
;; MD-roam for Markdown support in Org-roam
(use-package! md-roam
  :after org-roam
  :config 
  ;; (set-company-backend! 'markdown-mode 'company-capf)
  (setq org-roam-file-extensions '("org" "md"))
  (md-roam-mode 1)
  (setq md-roam-file-extension '("md" "markdown")) ; default "md". Specify an extension such as "markdown"
  (add-to-list 'org-roam-capture-templates
               '("m" "Markdown" plain "" :target
                 (file+head "10-Inbox/%<%Y%m%dT%H%M%S>-${slug}..md"
                            "---\ntitle: ${title}\nid: %<%Y-%m-%dT%H%M%S>\ncategory: \n---\n")
                 :unnarrowed t))
  (org-roam-db-autosync-mode 1)
  )
```
It worked fine with org-roam ui.

**Comment by nobiot** [comment]
When you write [[wikilink]], what is wikilink? Is it a file name, title, or the ID?

**Comment by Ravenightwing** [comment]
> When you write [[wikilink]], what is wikilink? Is it a file name, title, or the ID?

I tried both the title and ID, but neither worked.

**Comment by nobiot** [comment]
Have you toggled on the wikilink within markdown mode?

**Comment by Ravenightwing** [comment]
> Have you toggled on the wikilink within markdown mode?

My bad, thank you so much!!!
