### ISSUE TITLE
Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer

### ISSUE THREAD

**Issue by hyperfocus1337** [nobiot/md-roam#88]
Once I create a markdown note using `org-roam-capture`, it triggers the following in the warning buffer:

```elisp
⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer 20241003195612-askldfjsdafsdfasdf.md> (markdown-mode)
```

This function seems to be present [here](https://github.com/org-roam/org-roam/blob/main/org-roam-capture.el#L670) in the [org-roam](https://github.com/org-roam/org-roam/) repository. Couldn't find it being used in this repository.

My Emacs lisp skills are insufficient to tackle this issue. Hopefully this can be fixed at some point.

Using the following [code](https://github.com/doomemacs/doomemacs/blob/master/modules/lang/org/packages.el#L106-L111) in Doom Emacs to install org-roam.
```
 (modulep! +roam2)
  (package! org-roam
    ;; FIXME A :recipe isn't strictly necessary, but without it, our package
    ;;       bumper fails to distinguish between org-roam v1 and v2.
    :recipe (:host github :repo "org-roam/org-roam")
    :pin "0b9fcbc97b65b349826e63bad89ca121a08fd2be")
```

**Comment by nobiot** [comment]
What's the real problem here for you? I get these warnings logged in the buffer and just let them be -- as far as I can tell, they do any harm. I also create my notes in various ways, and org-roam-capture is only one way.

If your setting gets the warning to pop up, you can use customization to let it quietly sit in the log. I believe this should be the default behavior of warning messages

**Comment by nobiot** [comment]
It looks like you are no linger using md-roam or org-roam: https://github.com/protesilaos/denote/issues/454#issue-2573361934

closing.

**Comment by hyperfocus1337** [comment]
Thank you for your feedback. I didn't think of muting that warning, that would then indeed be able to solve it.
